#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 12 15:37:32 2019

@author: minhlkieu

This is a Gaussian Process Emulator of an Agent-based model

It needs the Input and Output from an ABM, it then aims to emulate a Step transition 
function in an ABM


"""

import os
import numpy as np
#import gp_emulator
os.chdir("/Users/minhlkieu/Documents/dust/Projects/GP_Emulator")
#from GaussianProcess import GaussianProcess
from MultiOutputGP import MultiOutputGP


import pickle

#load simulated data
data = np.genfromtxt('data_emulator.csv', delimiter=',')

#process data to make predictions
x = data[1:-1,]
y=data[2:,] 

Num_model = 100
for m in range(0,100):
	
	#Threshold = 
	
	train_idx = np.random.randint(0,np.size(x[:,1]),400)
	
	x_train = x[train_idx,:]
	y_train = y[train_idx].T
	
	gp1 = MultiOutputGP(x_train, y_train)
	gp1.learn_hyperparameters(n_tries=25)
	# save the model to disk
	
	#filename = 'gp_emulator.sav'
	filename = "gp_emulator_%d.sav" % m
	
	pickle.dump(gp1, open(filename, 'wb'))
